//
// Copyright 2022 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: testv3.proto

package grpc_testing_not_regenerate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchResponseV3_State int32

const (
	SearchResponseV3_UNKNOWN SearchResponseV3_State = 0
	SearchResponseV3_FRESH   SearchResponseV3_State = 1
	SearchResponseV3_STALE   SearchResponseV3_State = 2
)

// Enum value maps for SearchResponseV3_State.
var (
	SearchResponseV3_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "FRESH",
		2: "STALE",
	}
	SearchResponseV3_State_value = map[string]int32{
		"UNKNOWN": 0,
		"FRESH":   1,
		"STALE":   2,
	}
)

func (x SearchResponseV3_State) Enum() *SearchResponseV3_State {
	p := new(SearchResponseV3_State)
	*p = x
	return p
}

func (x SearchResponseV3_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchResponseV3_State) Descriptor() protoreflect.EnumDescriptor {
	return file_testv3_proto_enumTypes[0].Descriptor()
}

func (SearchResponseV3_State) Type() protoreflect.EnumType {
	return &file_testv3_proto_enumTypes[0]
}

func (x SearchResponseV3_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchResponseV3_State.Descriptor instead.
func (SearchResponseV3_State) EnumDescriptor() ([]byte, []int) {
	return file_testv3_proto_rawDescGZIP(), []int{0, 0}
}

type SearchResponseV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*SearchResponseV3_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	State   SearchResponseV3_State     `protobuf:"varint,2,opt,name=state,proto3,enum=grpc.testingv3.SearchResponseV3_State" json:"state,omitempty"`
}

func (x *SearchResponseV3) Reset() {
	*x = SearchResponseV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testv3_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponseV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponseV3) ProtoMessage() {}

func (x *SearchResponseV3) ProtoReflect() protoreflect.Message {
	mi := &file_testv3_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponseV3.ProtoReflect.Descriptor instead.
func (*SearchResponseV3) Descriptor() ([]byte, []int) {
	return file_testv3_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResponseV3) GetResults() []*SearchResponseV3_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponseV3) GetState() SearchResponseV3_State {
	if x != nil {
		return x.State
	}
	return SearchResponseV3_UNKNOWN
}

type SearchRequestV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *SearchRequestV3) Reset() {
	*x = SearchRequestV3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testv3_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequestV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequestV3) ProtoMessage() {}

func (x *SearchRequestV3) ProtoReflect() protoreflect.Message {
	mi := &file_testv3_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequestV3.ProtoReflect.Descriptor instead.
func (*SearchRequestV3) Descriptor() ([]byte, []int) {
	return file_testv3_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequestV3) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchResponseV3_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string                                    `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title    string                                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets []string                                  `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	Metadata map[string]*SearchResponseV3_Result_Value `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SearchResponseV3_Result) Reset() {
	*x = SearchResponseV3_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testv3_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponseV3_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponseV3_Result) ProtoMessage() {}

func (x *SearchResponseV3_Result) ProtoReflect() protoreflect.Message {
	mi := &file_testv3_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponseV3_Result.ProtoReflect.Descriptor instead.
func (*SearchResponseV3_Result) Descriptor() ([]byte, []int) {
	return file_testv3_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearchResponseV3_Result) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResponseV3_Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResponseV3_Result) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *SearchResponseV3_Result) GetMetadata() map[string]*SearchResponseV3_Result_Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponseV3_Result_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Val:
	//
	//	*SearchResponseV3_Result_Value_Str
	//	*SearchResponseV3_Result_Value_Int
	//	*SearchResponseV3_Result_Value_Real
	Val isSearchResponseV3_Result_Value_Val `protobuf_oneof:"val"`
}

func (x *SearchResponseV3_Result_Value) Reset() {
	*x = SearchResponseV3_Result_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testv3_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponseV3_Result_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponseV3_Result_Value) ProtoMessage() {}

func (x *SearchResponseV3_Result_Value) ProtoReflect() protoreflect.Message {
	mi := &file_testv3_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponseV3_Result_Value.ProtoReflect.Descriptor instead.
func (*SearchResponseV3_Result_Value) Descriptor() ([]byte, []int) {
	return file_testv3_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (m *SearchResponseV3_Result_Value) GetVal() isSearchResponseV3_Result_Value_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (x *SearchResponseV3_Result_Value) GetStr() string {
	if x, ok := x.GetVal().(*SearchResponseV3_Result_Value_Str); ok {
		return x.Str
	}
	return ""
}

func (x *SearchResponseV3_Result_Value) GetInt() int64 {
	if x, ok := x.GetVal().(*SearchResponseV3_Result_Value_Int); ok {
		return x.Int
	}
	return 0
}

func (x *SearchResponseV3_Result_Value) GetReal() float64 {
	if x, ok := x.GetVal().(*SearchResponseV3_Result_Value_Real); ok {
		return x.Real
	}
	return 0
}

type isSearchResponseV3_Result_Value_Val interface {
	isSearchResponseV3_Result_Value_Val()
}

type SearchResponseV3_Result_Value_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,proto3,oneof"`
}

type SearchResponseV3_Result_Value_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type SearchResponseV3_Result_Value_Real struct {
	Real float64 `protobuf:"fixed64,3,opt,name=real,proto3,oneof"`
}

func (*SearchResponseV3_Result_Value_Str) isSearchResponseV3_Result_Value_Val() {}

func (*SearchResponseV3_Result_Value_Int) isSearchResponseV3_Result_Value_Val() {}

func (*SearchResponseV3_Result_Value_Real) isSearchResponseV3_Result_Value_Val() {}

var File_testv3_proto protoreflect.FileDescriptor

var file_testv3_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x76, 0x33, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x22, 0x9b,
	0x04, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x56, 0x33, 0x12, 0x41, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0xd9, 0x02, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70,
	0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70,
	0x65, 0x74, 0x73, 0x12, 0x51, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x4c, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x73, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x00, 0x52, 0x03, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x42, 0x05, 0x0a,
	0x03, 0x76, 0x61, 0x6c, 0x1a, 0x6a, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x43, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x2a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x52, 0x45, 0x53, 0x48, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x22, 0x27, 0x0a, 0x0f,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x33, 0x12,
	0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x32, 0xb8, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x56, 0x33, 0x12, 0x4b, 0x0a, 0x06, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x56, 0x33, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x12, 0x58, 0x0a, 0x0f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x33, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x33, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e,
	0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x66, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testv3_proto_rawDescOnce sync.Once
	file_testv3_proto_rawDescData = file_testv3_proto_rawDesc
)

func file_testv3_proto_rawDescGZIP() []byte {
	file_testv3_proto_rawDescOnce.Do(func() {
		file_testv3_proto_rawDescData = protoimpl.X.CompressGZIP(file_testv3_proto_rawDescData)
	})
	return file_testv3_proto_rawDescData
}

var file_testv3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testv3_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testv3_proto_goTypes = []interface{}{
	(SearchResponseV3_State)(0),           // 0: grpc.testingv3.SearchResponseV3.State
	(*SearchResponseV3)(nil),              // 1: grpc.testingv3.SearchResponseV3
	(*SearchRequestV3)(nil),               // 2: grpc.testingv3.SearchRequestV3
	(*SearchResponseV3_Result)(nil),       // 3: grpc.testingv3.SearchResponseV3.Result
	(*SearchResponseV3_Result_Value)(nil), // 4: grpc.testingv3.SearchResponseV3.Result.Value
	nil,                                   // 5: grpc.testingv3.SearchResponseV3.Result.MetadataEntry
}
var file_testv3_proto_depIdxs = []int32{
	3, // 0: grpc.testingv3.SearchResponseV3.results:type_name -> grpc.testingv3.SearchResponseV3.Result
	0, // 1: grpc.testingv3.SearchResponseV3.state:type_name -> grpc.testingv3.SearchResponseV3.State
	5, // 2: grpc.testingv3.SearchResponseV3.Result.metadata:type_name -> grpc.testingv3.SearchResponseV3.Result.MetadataEntry
	4, // 3: grpc.testingv3.SearchResponseV3.Result.MetadataEntry.value:type_name -> grpc.testingv3.SearchResponseV3.Result.Value
	2, // 4: grpc.testingv3.SearchServiceV3.Search:input_type -> grpc.testingv3.SearchRequestV3
	2, // 5: grpc.testingv3.SearchServiceV3.StreamingSearch:input_type -> grpc.testingv3.SearchRequestV3
	1, // 6: grpc.testingv3.SearchServiceV3.Search:output_type -> grpc.testingv3.SearchResponseV3
	1, // 7: grpc.testingv3.SearchServiceV3.StreamingSearch:output_type -> grpc.testingv3.SearchResponseV3
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_testv3_proto_init() }
func file_testv3_proto_init() {
	if File_testv3_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testv3_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponseV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testv3_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequestV3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testv3_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponseV3_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testv3_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponseV3_Result_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_testv3_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*SearchResponseV3_Result_Value_Str)(nil),
		(*SearchResponseV3_Result_Value_Int)(nil),
		(*SearchResponseV3_Result_Value_Real)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testv3_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testv3_proto_goTypes,
		DependencyIndexes: file_testv3_proto_depIdxs,
		EnumInfos:         file_testv3_proto_enumTypes,
		MessageInfos:      file_testv3_proto_msgTypes,
	}.Build()
	File_testv3_proto = out.File
	file_testv3_proto_rawDesc = nil
	file_testv3_proto_goTypes = nil
	file_testv3_proto_depIdxs = nil
}
